name: Crossterm Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  crossterm_rust:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-10.14]
        rust: [stable, nightly]
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Add Component
      run: rustup component add rustfmt
    - name: Run Build
      run: cargo build
    - name: Check Examples
      run: cargo check --examples 
    - name: Run Tests
      if: matrix.os == 'windows-2019'
      run: cargo test --all -- --nocapture --test-threads 1
    - name: Run Tests if not Windows
      if: matrix.os != 'windows-2019'
      run: cargo test --all --exclude crossterm_winapi -- --nocapture --test-threads 1
    - name: Run FMT
      if: matrix.os == 'windows-2019'
      run: cargo fmt --all -- --check
    - name: Run FMT if not Windows
      if: matrix.os != 'windows-2019'
      run: cargo fmt --all --exclude crossterm_winapi -- --check
      
